languange: generic
sudo: required
services:
 - docker

before_install:
 - docker build -t jldocker954/docker-react -f dockerfile.dev .

script:
 - docker run -e CI=true jldocker954/docker-react npm run test

deploy:
 provider: elasticbeanstalk
 region: "us-east-1"
 app: "docker"
 env: "docker-env"
 bucket_name: "elasticbeanstalk-us-east-1-512636610551"
 bucket_path: "docker"
 on:
   branch: master
 access_key_id: $AWS_ACCESS_KEY
 secret_access_key: $AWS_SECRECT_KEY 